# Generated by Django 5.0.1 on 2024-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_rename_distance_additional_pricing_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('waittime', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='distance',
            new_name='distance_add',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='time',
            new_name='distance_base',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='wait',
            new_name='tmf',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='day',
        ),
        migrations.AddField(
            model_name='pricing',
            name='wc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
