# Generated by Django 5.0.1 on 2024-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_ride_rename_distance_pricing_distance_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
