# Generated by Django 5.0.1 on 2024-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_pricing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='distance_add',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='distance_base',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='tmf',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='wc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='starttime',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='waittime',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
