# Generated by Django 5.0.1 on 2024-01-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_alter_pricing_distance_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
