# Generated by Django 5.0.1 on 2024-01-08 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_pricing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='starttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='waittime',
            field=models.DateTimeField(),
        ),
    ]
