# Generated by Django 5.0.1 on 2024-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_pricing_created_at_pricing_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='distance_add',
            new_name='distance_add_tier1',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='distance_base',
            new_name='distance_add_tier2',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='tmf',
            new_name='distance_base_tier1',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='wc',
            new_name='distance_base_tier2',
        ),
        migrations.AddField(
            model_name='pricing',
            name='distance_base_tier3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='tmf_tier1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='tmf_tier2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='tmf_tier3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='wc_tier1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='wc_tier2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
