# Generated by Django 5.0.1 on 2024-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_rename_distance_add_pricing_distance_add_tier1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='totalhours',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='totalprice',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='starttime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='waittime',
            field=models.CharField(max_length=50),
        ),
    ]
