# Generated by Django 5.0.1 on 2024-01-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0011_alter_ride_endtime_alter_ride_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='totalhours',
            field=models.FloatField(),
        ),
    ]
