# Generated by Django 5.0.1 on 2024-01-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0013_alter_ride_waittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
