# Generated by Django 5.0.1 on 2024-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_alter_ride_endtime_alter_ride_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='starttime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ride',
            name='totalhours',
            field=models.CharField(max_length=50),
        ),
    ]
